#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='code -w';

# Increase Bash history size. Allow 32^3 entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG="en_US.UTF-8"
export LANGUAGE=$LANG
export LC_ALL="en_US.UTF-8"

# Don't clear the screen after quitting a manual page.
export MANPAGER='less -X';

PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
export PROMPT_COMMAND="${PROMPT_TITLE}; ${PROMPT_COMMAND}"

export BLACKFIRE_CLIENT_ID='4dbd8478-27a8-4b47-b389-a71cf039a654';
export BLACKFIRE_CLIENT_TOKEN='3cdc216a93c135acb049f97dbcabe75a89359e9bbe5fd611fd85141a3261b2ec';
export BLACKFIRE_SERVER_ID='8530fb74-9bb6-43e4-af18-745b98a25fc1';
export BLACKFIRE_SERVER_TOKEN='503a7c7a1f453b9e42727e0c9961e5103c959776fac186c9d754773e59e6eb99';
export FASTLY_API_TOKEN='ks5dnuWjkhox4Nx00iQ9aoYt2qnJiyJZ';
export FASTLY_API_KEY="$FASTLY_API_TOKEN";
