// Generated by Finicky Kickstart
// Save as ~/.finicky.js

const CHROME_PWAS = {
	meet: "kjgfgldnnfoeklkmfkjfagphfepbbdan",
	gmail: "fmgjjmmmlfnkbppncabfkddbjimcfncm",
};

const openChromePWA = (app = "", url = "", name = "Google Chrome") => {
	return {
		name: name,
		args: [
			`--app-id=${CHROME_PWAS[app]}`,
			`--app-launch-url-for-shortcuts-menu-item=${url}`,
		],
	};
};

module.exports = {
	defaultBrowser: "Google Chrome",
	options: {
		hideIcon: true,
	},
	handlers: [
		{
			match: ({ opener, url }) =>
				opener.name === "Meeter" && url.host.includes("google.com"),
			browser: ({ urlString, url }) => {
				const meetingUrl = url.search.replace(/^.*continue=([^&]+).*$/, "$1");
				return openChromePWA("meet", meetingUrl);
			},
		},
		{
			match: ({ url }) => url.host === "meet.google.com",
			browser: ({ urlString }) => openChromePWA("meet", urlString),
		},
		{
			match: ({ url }) => url.host === "mail.google.com",
			browser: ({ urlString }) => openChromePWA("gmail", urlString),
		},
	],
};
