#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ..... and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Act safely when modifying files
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Detect which `ls` flavor is in use
if ls --color >/dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export CLICOLOR=1
	export LS_COLORS='di=36:ln=1;31:so=37:pi=1;33:ex=35:bd=37:cd=37:su=37:sg=37:tw=32:ow=32:'
else # macOS `ls`
	colorflag="-G"
	export CLICOLOR=1
	export LSCOLORS='gxBxhxDxfxhxhxhxhxcxcx'
fi

# List all files colorized in long format
alias ll="ls -lF ${colorflag}"

# List all files colorized including dot files, excluding . and ..
alias la="ls -AF ${colorflag}"

# List all files colorized including dot files in long format, excluding . and ..
alias lal="ls -lAF ${colorflag}"

# Always use color output and no quoting for `ls`
alias ls="command ls ${colorflag}"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an extended regex version of find (like egrep)
alias efind='find -E'

# Typos
alias 'cd..'='cd ..'
alias 'ls-al'='ls -al'

# Trim new lines and copy to clipboard
alias cb="ghead -c -1 | pbcopy"

# Extra names and functions
alias edit="/usr/local/bin/code -a"
alias uglify-es="terser"

# Common shortcuts
alias edithosts="/usr/local/bin/code -a /etc/hosts"
alias editprof="/usr/local/bin/code -a ~/.bash_profile"
alias fdirs='find . -type d'
alias fdotdash="find . -name '._*'"
alias fdsstore="find . -name '.DS_Store'"
alias ffiles='find . -type f'

# Virtualization shortcuts
#alias hs="homestead"
#alias hsstart="homestead up && homestead ssh"
#alias vmrun='/usr/local/bin/vmrun -T fusion'
#alias ubunboot='/usr/local/bin/vmrun -T fusion start "$HOME/Virtual Machines/Ubuntu 64-bit.vmwarevm/Ubuntu 64-bit.vmx" nogui'
#alias shubuntu='ssh jeremy@10.1.1.10'

# Make Grunt print stack traces by default
#command -v grunt > /dev/null && alias grunt="grunt --stack"

# Show/hide hidden files in Finder
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f \( -name '.DS_Store' -o -name '._*' \) -ls -delete"

# Enable aliases to be sudo'ed
alias sudo='sudo '

# Enable bash for sudo shell
alias lvlup='sudo -s'

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# IP info
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="networksetup -listallnetworkservices | grep -v '\*' | xargs -I{} networksetup -getinfo "{}" | tr '[:upper:]' '[:lower:]' | grep -E '^ip address: \d' | sed 's/ip address: //'"

# Set permisions to
alias modownf='find . -type f -print0 | xargs -0 -I{} chmod 644 {}'
alias modownd='find . -type d -print0 | xargs -0 -I{} chmod 755 {}'
alias modgrpf='find . -type f -print0 | xargs -0 -I{} chmod 664 {}'
alias modgrpd='find . -type d -print0 | xargs -0 -I{} chmod 775 {}'
#alias modallf='find . -type f -print0 | xargs -0 -I{} chmod 666 {}'
#alias modalld='find . -type d -print0 | xargs -0 -I{} chmod 777 {}'

if [[ -x $(which bat) ]]; then
	alias cat=bat
fi

# Git aliases for easier completion
alias gitbranch='git branch'
alias gitcheckout='git checkout'
alias gitcommit='git commit'
alias gitdiff='git diff'
alias gitlog='git log'
alias gitmerge='git merge'
alias gitpull='git pull'
alias gitpush='git push'
alias gitreset='git reset'
alias gitstatus='git status'
alias gits='git s'

alias f="gfind ! -path '*/.git/*' ! -path '*/vendor/*' ! -path '*/node_modules/*'"

alias nvmup='nvm install `nvm version-remote --lts` --lts'
alias nvmuplatest='nvm install `nvm version-remote`'

alias d='dev'
alias dup='dev up'
alias dups='dev up && dev server'
alias ddup='dev down && dev up'
alias ddups='dev down && dev up && dev server'
alias dct='TZ=UTC dev client-test'
alias dwc='TZ=UTC dev web-checks'
alias ddupup='dev down && dev update && dev up'
alias dcd='dev cd'
