#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='code -w';

# Increase Bash history size. Allow 32^3 entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG="en_US.UTF-8"
export LANGUAGE=$LANG
export LC_ALL="en_US.UTF-8"

# Don't clear the screen after quitting a manual page.
export MANPAGER='less -X';

PROMPT_TITLE='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'
export PROMPT_COMMAND="${PROMPT_TITLE}; ${PROMPT_COMMAND}"

