// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
	defaultBrowser: "Google Chrome",
	handlers: [
		{
			match: ({ opener, url }) => opener.name === 'Meeter' && url.host.includes("google.com"),
			browser: ({ urlString, url }) => {
				const meetingUrl = url.search.replace(/^.*continue=([^&]+).*$/, "$1");
				finicky.log(meetingUrl);
				return {
					name: "Google Chrome",
					args: [
						'--app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan',
						`--app-launch-url-for-shortcuts-menu-item=${meetingUrl}`,
					],
				}
			},
		}
	]
}
