# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

matches:

  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  # Print the current date as a datestamp
  - trigger: ";ds"
    replace: "{{mydatestamp}}"
    vars:
      - name: mydatestamp
        type: date
        params:
          format: "%Y%m%d"

  # Print the current time
  - trigger: ";time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M:%S"

  # Print the current time as a timestamp
  - trigger: ";ts"
    replace: "{{mytimestamp}}"
    vars:
      - name: mytimestamp
        type: date
        params:
          format: "%H%M%S"

  - trigger: ";wem"
    replace: "jeremy.tweddle@shopify.com"

  - trigger: ";pem"
    replace: "jeremy@breams.net"

  - trigger: ";tem"
    replace: "jeremy@tweddle.net"

  - trigger: ";fn"
    replace: "Jeremy"

  - trigger: ";ln"
    replace: "Tweddle"

  - trigger: ";name"
    replace: "Jeremy Tweddle"

  - trigger: ";ph"
    replace: "4379953595"

  - trigger: ";pc"
    replace: "L1S7R9"

  - trigger: ;ghnote
    replace: |
      > [!NOTE]
      > $|$

  - trigger: ;ghwarn
    replace: |
      > [!WARNING]
      > $|$

  - trigger: ;ghcaut
    replace: |
      > [!CAUTION]
      > $|$

  - trigger: ;ghimp
    replace: |
      > [!IMPORTANT]
      > $|$
